# Example of using SSP-VIKOR method

This is a simple example of using the SSP-VIKOR method. SSP-VIKOR is named in this code as VASSP. Its application is demonstrated in the illustrative example from the paper. This example shows the basic use of the SSP-VIKOR method. In this example, the ranking of evaluated alternatives is constructed for a sustainable coefficient set as 0.3 for each criterion. More complex procedures can be found in .py files in this repository.

Import of necessary Python packeges

In [1]:
import numpy as np
import pandas as pd

from pyrepo_mcda import normalizations as norms
from pyrepo_mcda.additions import rank_preferences
from pyrepo_mcda import weighting_methods as mcda_weights
from vassp import VASSP

Load the dataset of evaluated alternatives, for example, for the 2021 year, and save it in the pandas `dataframe`.

In [2]:
# Load Symbols of Countries
coun_names = pd.read_csv('./data/country_names.csv')
country_names = list(coun_names['Symbol'])

# Choose evaluated year: 2020 or 2021
year = '2021'
df_data = pd.read_csv('./data/data_' + year + '.csv', index_col='Country')

Display the dataset with performance values of evaluated alternatives (countries) concerning evaluation criteria (C1-C13).

In [3]:
df_data

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13
Country,,,,,,,,,,,,,
United States,0.000,0.000,0.00,0.00,2.770,0.00,58556.537,15168.834,1386.823,72.032,0.014147,1417.123,0.176779
Austria,9.555,5262.371,5.45,0.00,7.370,0.00,52604.155,11868.066,13233.999,74.842,0.010416,1063.525,0.092108
Belgium,0.000,0.000,0.00,0.00,5.640,4.93,50511.132,12948.271,1743.986,76.689,0.006281,767.982,0.032890
Bulgaria,0.000,0.000,0.00,0.00,7.454,0.00,36456.891,3342.987,904.108,28.805,0.043360,3453.262,0.393325
Czechia,0.000,0.000,0.00,0.00,6.630,0.00,112346.960,20646.675,4084.551,64.951,0.013991,2355.455,0.216567
Denmark,9.264,5453.023,0.00,0.00,2.500,0.00,15783.191,2590.290,7309.683,80.118,0.003335,332.065,0.031456
Finland,0.000,0.000,0.00,0.00,3.280,0.00,8934.355,1580.660,1119.220,77.435,0.005063,196.983,0.047004
France,0.000,0.000,0.00,0.00,5.980,0.00,88607.162,14475.361,2328.867,78.371,0.008316,881.300,0.051940
Germany,11.016,6350.865,4.53,0.00,8.000,0.00,218595.000,12105.297,688.914,75.060,0.014924,961.138,0.069396
Greece,0.000,0.000,0.00,0.00,4.210,0.00,4200.000,2491.200,4082.539,71.596,0.016135,1530.678,0.149173
Hungary,5.303,0.000,3.28,6.59,7.020,0.00,132247.102,3045.900,667.733,61.548,0.031873,2971.140,0.194288
Ireland,5.275,4575.532,4.05,12.80,2.960,0.00,32018.621,5650.880,1521.554,78.248,0.005653,734.343,0.077525
Italy,7.145,3051.572,4.13,6.26,3.180,0.00,74866.848,8341.530,1872.367,81.786,0.017172,1090.165,0.105252
Lithuania,5.507,2320.756,0.00,0.00,6.560,5.06,90120.640,4628.200,1886.254,69.394,0.014869,2066.396,0.306496
Luxembourg,0.000,0.000,0.00,0.00,4.510,3.22,32011.997,8089.836,3405.397,71.348,0.007876,668.859,-0.017338
Netherlands,9.551,5752.462,0.00,0.00,3.320,0.00,22918.158,8965.263,906.985,71.717,0.004176,553.548,0.097002
Norway,8.625,6044.488,5.18,18.37,3.600,0.00,8142.857,2846.900,1206.456,78.940,0.002532,156.153,0.036175
Poland,4.785,1863.608,0.00,0.00,6.620,0.00,101791.889,3240.320,528.472,54.167,0.024186,1701.611,0.223250
Portugal,7.171,2441.070,0.00,0.00,3.390,0.00,44826.740,7614.164,1971.867,91.636,0.013306,1189.633,0.082465
Romania,0.000,0.000,0.00,0.00,6.892,0.00,112978.357,2316.769,630.598,30.503,0.036536,2201.216,0.285800
Slovakia,0.000,0.000,0.00,0.00,5.820,0.00,106567.694,17871.670,7948.748,44.756,0.013184,2585.799,0.344704
Slovenia,6.828,2787.512,0.00,0.00,4.500,0.00,88757.991,19829.306,661.804,58.576,0.008661,1398.485,0.101913
Spain,0.000,0.000,0.00,0.00,2.970,0.00,50710.176,12992.130,1048.113,83.424,0.009306,820.071,0.063362
Sweden,9.787,5358.066,0.00,10.85,2.220,0.00,31702.904,5318.717,1043.652,72.624,0.007819,652.269,0.025858
Switzerland,0.000,0.000,4.45,0.00,4.530,0.00,35607.921,7751.984,1261.003,68.158,0.005351,513.403,0.050554
United Kingdom,9.898,4466.127,3.18,8.68,2.540,0.00,49970.983,5875.549,5061.414,74.079,0.008346,1247.407,0.090292

Provide criteria types: 1 for profit criteria and -1 for cost criteria.

In [4]:
types = np.array([1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, -1])

Convert the decision matrix from the `dataframe` type to `numpy.ndarray` matrix because the VASSP method (SSP-VIKOR) takes such a data type.

In [5]:
matrix = df_data.to_numpy()

Determine criteria importance values (criteria weights), for example, using the objective weighting method CRITIC from the `pyrepo-mcda` Python package.

In [6]:
weights = mcda_weights.critic_weighting(matrix)

Initialize the object of the SSP-VIKOR method.

In [7]:
vassp = VASSP()

Assign sustainability coefficient values for each criterion as a real value from 0.0 to 1.0. In this example, the s coefficient value for each criterion is set as 0.3.

In [8]:
s_coeffs = np.ones(matrix.shape[1]) * 0.3

Calculate SSP-VIKOR preference values for evaluated alternatives.

In [9]:
pref_vassp = vassp(matrix, weights, types, s_coeff = s_coeffs)

Rank alternatives according to SSP-VIKOR preference values, sorting them in ascending order. In the SSP-VIKOR, as in the classical VIKOR method, the alternative with the lowest preference value is the best evaluated ranking leader.

In [10]:
rank_vassp = rank_preferences(pref_vassp, reverse = False)

Save preference values and ranks of alternatives in `dataframe` to display them below.

In [11]:
df_results = pd.DataFrame(index = country_names)
df_results['Preference value'] = pref_vassp
df_results['Rank'] = rank_vassp

In [12]:
df_results

     Preference value  Rank
USA          0.926915    22
AUT          0.045679     2
BEL          0.761112    15
BGR          1.000000    26
CZE          0.936367    23
DNK          0.439964     7
FIN          0.811473    18
FRA          0.847336    20
DEU          0.124507     5
GRC          0.837564    19
HUN          0.796835    17
IRL          0.112902     3
ITA          0.172036     6
LTU          0.515499    10
LUX          0.764558    16
NLD          0.491855     9
NOR          0.000000     1
POL          0.620096    12
PRT          0.541221    11
ROU          0.964319    25
SVK          0.964167    24
SVN          0.625114    13
ESP          0.874872    21
SWE          0.454099     8
CHE          0.759922    14
GBR          0.118214     4

It can be noted that Norway (NOR) is the best evaluated country. Austria (AUT) is second in the ranking, and Ireland (IRL) comes third.